### ISSUE TITLE
Regex-Filters don't apply to new pipelines

### ISSUE THREAD

**Issue by flosell** [karmats/gocd-monitor#55]
In my current team, we are only interested in a few of the pipelines in GoCD (our our own teams' pipelines plus a few shared ones, not other teams' pipelines) so we set up a regex to filter out whatever we aren't interested in, expecting it would also filter any new pipelines that might pop up in the future (which happens quite regularly in our case). 
Unfortunately, digging deeper into the code, I found that this doesn't happen. The regex is only used in the actual configuration step to determine `disabledPipelines`.

I'm happy to submit a fix for this but I'm wondering what the intended behaviour should be.
My intuition would say filter by regex, then remove any left-over disabled pipelines. However, you could also do either regex or disabled pipelines. 

Any opinions? 
Apart fom that, any good ideas how to make the behaviour more obvious to the user?

**Comment by karmats** [comment]
Yes, it should indeed be like you're suggesting, and I would love if you did some improvements for that feature. In my opinion the "Update regex"-button is also a bit confusing since it doesn't seems to do anything when pressing it. So either remove it or make the pipelines that will be disabled to switch when pressing it. Also the switch doesn't really add much value.

If I would implement that feature I would probably just have the input-field and if something is typed the regex should be used when fetching the pipelines and maybe the pipelines that doesn't match the regex should also disappear from the list? What do you think?

**Comment by flosell** [comment]
Thanks for the feedback! I played with the UI components a bit, I think we can keep the overall structure the same (allowing users to disable individual pipelines but also make the regex work properly): https://codesandbox.io/s/8umnx

What do you think? Does this make sense?

**Comment by karmats** [comment]
Love it! 👌

**Comment by karmats** [comment]
Fixed in #56
